//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AngineEditor.rc
//
#define IDR_AEPROJECT_TYPE_CNTR_IP      7
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_PROJECT_PROPERTIES          101
#define IDP_FAILED_TO_CREATE            102
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_EFFECTVIEW_TOOLBAR          185
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDR_AEPROJECT_TYPE              220
#define IDR_HLSLFILE_TYPE               221
#define IDR_GLSLFILE_TYPE               222
#define IDR_EFFECTFILE_TYPE             223
#define ID_EFFECTVIEW_ADDNEW            224
#define IDR_FXFILE_TYPE                 224
#define ID_EFFECTVIEW_REMOVE            225
#define ID_EFFECTVIEW_EDITCTRL          226
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_NEWPROJECTDLG               310
#define IDD_ADDNEWPROFILEDLG            312
#define IDB_EFFECTVIEW_TOOLBAR          316
#define IDB_EFFECTVIEW_TOOLBAR_HC       316
#define IDD_DIALOGBAR                   316
#define IDB_ADD_BUTTON                  322
#define IDB_SUB_BUTTON                  323
#define IDB_ADD_SUB_BUTTON              329
#define IDC_VSPROP                      331
#define IDC_PSPROP                      332
#define IDB_UP_BUTTON                   334
#define IDB_UP_BUTTON_                  334
#define IDB_UP_BUTTON_d                 334
#define IDB_DOWN_BUTTON                 335
#define IDB_MOD_BUTTON                  336
#define IDD_DIALOG1                     341
#define IDD_TEXTSTYLE_DLG               344
#define IDC_NP_EDITNAME                 1000
#define IDC_PN_BTNBROWSE                1001
#define IDC_NP_LISTCTRL                 1002
#define IDC_NP_EDITPATH                 1003
#define IDC_EFFECTVIEW_PROPERTYGRID     1004
#define IDC_EFFECTVIEW_TAB              1014
#define IDC_ADDNEWPROFILE_TARGET_COMBO  1017
#define IDC_ADDNEWPROFILE_TARGET_LABEL  1018
#define IDC_ADDNEWPROFILE_COPYFROM_LABEL 1022
#define IDC_ADDNEWPROFILE_COPYFROM_COMBO 1023
#define IDC_EFFECTVIEW_EFFECTPICKER_COMBO 1024
#define IDC_EFFECTVIEW_ADDNEWEFFECT_BUTTON 1025
#define IDC_EFFECTVIEW_RENAMEEFFECT_BUTTON 1026
#define IDC_EFFECTVIEW_PROFILEPICKER_COMBO 1027
#define IDC_EFFECTVIEW_ADDNEWPROFILE_BUTTON 1028
#define IDC_EFFECTVIEW_PROFILEADDNEW_BUTTON 1028
#define IDC_EFFECTVIEW_REMOVEPROFILE_BUTTON 1029
#define IDC_EFFECTVIEW_PROFILEREMOVE_BUTTON 1029
#define IDC_EFFECTVIEW_REMOVEEFFECT_BUTTON 1030
#define IDC_EFFECTVIEW_PASSPICKER_COMBO 1030
#define IDC_EFFECTVIEW_TECHNIQUEPICKER_COMBO 1031
#define IDC_EFFECTVIEW_TECHNIQUEADDNEW_BUTTON 1032
#define IDC_EFFECTVIEW_TECHNIQUEREMOVE_BUTTON 1033
#define IDC_EFFECTVIEW_GROUP1           1034
#define IDC_EFFECTVIEW_GROUP2           1035
#define IDC_EFFECTVIEW_GROUP3           1036
#define IDC_EFFECTVIEW_PASSADDNEW_BUTTON 1037
#define IDC_EFFECTVIEW_PASSREMOVE_BUTTON2 1038
#define IDC_EFFECTVIEW_GROUP4           1039
#define IDC_EFFECTVIEW_GROUP5           1040
#define IDC_EFFECTVIEW_GROUP6           1041
#define IDC_MFCPROPERTYGRID1            1042
#define IDC_MFCPROPERTYGRID2            1043
#define IDC_MFCBUTTON1                  1044
#define IDC_MFCBUTTON2                  1045
#define IDC_MFCBUTTON3                  1046
#define IDC_MFCBUTTON4                  1047
#define IDC_BUTTON1                     1048
#define IDC_MFCBUTTON5                  1048
#define IDC_EDIT1                       1066
#define IDC_FONTSIZE_EDIT               1066
#define IDC_EDIT2                       1067
#define IDC_CUSTOM_EDIT                 1067
#define IDC_LIST1                       1068
#define IDC_CATEGORY_LIST               1068
#define IDC_COLORBUTTON                 1094
#define IDC_FOREGROUNDCOLORPICKER_BUTTON 1095
#define IDC_BACKGROUNDCOLORPICKER_BUTTON 1096
#define IDC_STYLEPICKER_COMBO           1098
#define IDC_TEXTFONT_COMBO              1099
#define IDC_FONTSIZE_SPIN               1100
#define IDC_BOLD_CHECK                  1101
#define IDC_ITALIC_CHECK                1102
#define IDC_STRIKEOUT_CHECK             1103
#define IDC_UNDERLINE_CHECK             1104
#define IDC_SAMPLE_STATIC               1105
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_FILE_NEWPROJECT              32771
#define ID_FILE_OPENPROJECT             32772
#define ID_APPLICATIONLOOK_WINDOWS7     32774
#define ID_BUTTON32775                  32775
#define ID_EFFECTVIEW_UP                32776
#define ID_EFFECTVIEW_DOWN              32777
#define ID_EFFECTVIEW_ADDPROFILE        32778
#define ID_EFFECTVIEW_REMOVEPROFILE     32779
#define ID_BUTTON32780                  32780
#define ID_BUTTON32781                  32781
#define ID_EFFECTVIEW_MODIFY            32782

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        347
#define _APS_NEXT_COMMAND_VALUE         32783
#define _APS_NEXT_CONTROL_VALUE         1106
#define _APS_NEXT_SYMED_VALUE           316
#endif
#endif
